// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tutorium.AuthService.Infrastructure.Postgres;

#nullable disable

namespace Tutorium.AuthService.Infrastructure.Postgres.Data.Migrations.v0_1
{
    [DbContext(typeof(PgContext))]
    partial class PgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tutorium.AuthService.Core.Identity.Entities.EmailAuthentication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EmailAuthentications");
                });

            modelBuilder.Entity("Tutorium.AuthService.Core.Identity.UserAuthentication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ByEmailId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ByEmailId");

                    b.ToTable("UserAuthentications");
                });

            modelBuilder.Entity("Tutorium.AuthService.Core.Identity.Entities.EmailAuthentication", b =>
                {
                    b.OwnsOne("Tutorium.AuthService.Core.Identity.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<int>("EmailAuthenticationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("EmailAuthenticationId");

                            b1.ToTable("EmailAuthentications");

                            b1.WithOwner()
                                .HasForeignKey("EmailAuthenticationId");
                        });

                    b.OwnsOne("Tutorium.AuthService.Core.Shared.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("EmailAuthenticationId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("EmailAuthenticationId");

                            b1.ToTable("EmailAuthentications");

                            b1.WithOwner()
                                .HasForeignKey("EmailAuthenticationId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();
                });

            modelBuilder.Entity("Tutorium.AuthService.Core.Identity.UserAuthentication", b =>
                {
                    b.HasOne("Tutorium.AuthService.Core.Identity.Entities.EmailAuthentication", "ByEmail")
                        .WithMany()
                        .HasForeignKey("ByEmailId");

                    b.Navigation("ByEmail");
                });
#pragma warning restore 612, 618
        }
    }
}
